services:
  frontend:
    image: brapicoordinatorselby/brava-tools-fe:latest
    depends_on:
      - backend

  backend:
    image: brapicoordinatorselby/brava-tools-be:latest
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    
networks:
    default:
        name: brapi_net
        external: true
