services:
  frontend:
    image: brava-tools-fe
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    image: brava-tools-be
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=development
    ports:
      - "8080:8080"