services:
  frontend:
    image: brapicoordinatorselby/brava-tools-fe:latest
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    image: brapicoordinatorselby/brava-tools-be:latest
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"